#!/usr/bin/env bash
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TMPDIR="$(mktemp -d)"
trap 'rm -rf "$TMPDIR"' EXIT

. "$REPO_ROOT/scripts/lib-copies.sh"

mkdir -p "$TMPDIR/src/scripts"
printf '%s\n' '---' 'name: t' '---' > "$TMPDIR/src/SKILL.md"
printf 'x\n' > "$TMPDIR/src/scripts/run.sh"

# Fresh copy: creates dir, content, and ownership marker.
install_skill_copy "$TMPDIR/src" "$TMPDIR/dst/a"
test -f "$TMPDIR/dst/a/SKILL.md"
test -f "$TMPDIR/dst/a/scripts/run.sh"
test "$(cat "$TMPDIR/dst/a/.agent-scripts-copy")" = "$TMPDIR/src"

# Re-run over an owned copy: syncs deletions and keeps the marker.
rm "$TMPDIR/src/scripts/run.sh"
install_skill_copy "$TMPDIR/src" "$TMPDIR/dst/a"
test ! -e "$TMPDIR/dst/a/scripts/run.sh"
test -f "$TMPDIR/dst/a/.agent-scripts-copy"

# Legacy symlink destination: replaced by a real owned copy.
ln -s "$TMPDIR/src" "$TMPDIR/dst/b" 2>/dev/null || true
if [ -L "$TMPDIR/dst/b" ]; then
  install_skill_copy "$TMPDIR/src" "$TMPDIR/dst/b"
  test ! -L "$TMPDIR/dst/b"
  test -f "$TMPDIR/dst/b/.agent-scripts-copy"
fi

# Legacy lib-links fallback copy (.agent-scripts-copy-source): adopted.
mkdir -p "$TMPDIR/dst/e"
printf 'old-target\n' > "$TMPDIR/dst/e/.agent-scripts-copy-source"
printf 'stale\n' > "$TMPDIR/dst/e/leftover.txt"
install_skill_copy "$TMPDIR/src" "$TMPDIR/dst/e"
test -f "$TMPDIR/dst/e/.agent-scripts-copy"
test ! -e "$TMPDIR/dst/e/.agent-scripts-copy-source"
test ! -e "$TMPDIR/dst/e/leftover.txt"

# Pre-marker generated copy (SKILL.md matches upstream): adopted.
mkdir -p "$TMPDIR/dst/f"
cp "$TMPDIR/src/SKILL.md" "$TMPDIR/dst/f/SKILL.md"
printf 'stale\n' > "$TMPDIR/dst/f/leftover.txt"
install_skill_copy "$TMPDIR/src" "$TMPDIR/dst/f"
test -f "$TMPDIR/dst/f/.agent-scripts-copy"
test ! -e "$TMPDIR/dst/f/leftover.txt"

# Marker-less dir whose SKILL.md differs from upstream: refused.
mkdir -p "$TMPDIR/dst/g"
printf 'my own skill\n' > "$TMPDIR/dst/g/SKILL.md"
if install_skill_copy "$TMPDIR/src" "$TMPDIR/dst/g" 2>/dev/null; then
  echo "FAIL: overwrote a dir with a diverging SKILL.md" >&2
  exit 1
fi
test "$(cat "$TMPDIR/dst/g/SKILL.md")" = "my own skill"

# Non-owned, non-empty directory: refused, content untouched.
mkdir -p "$TMPDIR/dst/c"
printf 'user content\n' > "$TMPDIR/dst/c/mine.txt"
if install_skill_copy "$TMPDIR/src" "$TMPDIR/dst/c" 2>/dev/null; then
  echo "FAIL: overwrote a non-owned directory" >&2
  exit 1
fi
test "$(cat "$TMPDIR/dst/c/mine.txt")" = "user content"
test ! -e "$TMPDIR/dst/c/SKILL.md"

# Plain file destination: refused.
printf 'f\n' > "$TMPDIR/dst/d"
if install_skill_copy "$TMPDIR/src" "$TMPDIR/dst/d" 2>/dev/null; then
  echo "FAIL: replaced a plain file" >&2
  exit 1
fi

# gitignore block regen: replaces its own block, leaves others alone.
GI="$TMPDIR/.gitignore"
printf '%s\n' 'keep1' '# foo start (generated by x)' 'skills/old' '# foo end' 'keep2' > "$GI"
regen_gitignore_block "$GI" "foo" "test" "skills/new"
grep -qx 'skills/new' "$GI"
! grep -qx 'skills/old' "$GI"
grep -qx 'keep1' "$GI"
grep -qx 'keep2' "$GI"

# Unterminated block: refuses to rewrite instead of eating to EOF.
printf '%s\n' '# foo start (generated by x)' 'skills/old' 'keep-tail' > "$GI"
if regen_gitignore_block "$GI" "foo" "test" "skills/new" 2>/dev/null; then
  echo "FAIL: rewrote an unterminated block" >&2
  exit 1
fi
grep -qx 'keep-tail' "$GI"

echo "lib-copies tests passed"
