#!/usr/bin/env bash
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TMPDIR="$(mktemp -d)"
trap 'rm -rf "$TMPDIR"' EXIT

. "$REPO_ROOT/scripts/lib-copies.sh"

marker_source() { sed -n '1p' "$1"; }  # line 1 = upstream source path
marker_owner()  { sed -n '2p' "$1"; }   # line 2 = owning updater id

mkdir -p "$TMPDIR/src/scripts"
printf '%s\n' '---' 'name: t' '---' > "$TMPDIR/src/SKILL.md"
printf 'x\n' > "$TMPDIR/src/scripts/run.sh"

# Fresh copy: creates dir, content, and a two-line ownership marker.
install_skill_copy "$TMPDIR/src" "$TMPDIR/dst/a" owner-a
test -f "$TMPDIR/dst/a/SKILL.md"
test -f "$TMPDIR/dst/a/scripts/run.sh"
test "$(marker_source "$TMPDIR/dst/a/.agent-scripts-copy")" = "$TMPDIR/src"
test "$(marker_owner "$TMPDIR/dst/a/.agent-scripts-copy")" = "owner-a"

# Re-run over an owned copy: syncs deletions and keeps the two-line marker.
rm "$TMPDIR/src/scripts/run.sh"
install_skill_copy "$TMPDIR/src" "$TMPDIR/dst/a" owner-a
test ! -e "$TMPDIR/dst/a/scripts/run.sh"
test "$(marker_owner "$TMPDIR/dst/a/.agent-scripts-copy")" = "owner-a"

# Legacy symlink destination: replaced by a real owned copy.
ln -s "$TMPDIR/src" "$TMPDIR/dst/b" 2>/dev/null || true
if [ -L "$TMPDIR/dst/b" ]; then
  install_skill_copy "$TMPDIR/src" "$TMPDIR/dst/b" owner-b
  test ! -L "$TMPDIR/dst/b"
  test "$(marker_owner "$TMPDIR/dst/b/.agent-scripts-copy")" = "owner-b"
fi

# Legacy lib-links fallback copy (.agent-scripts-copy-source): adopted.
mkdir -p "$TMPDIR/dst/e"
printf 'old-target\n' > "$TMPDIR/dst/e/.agent-scripts-copy-source"
printf 'stale\n' > "$TMPDIR/dst/e/leftover.txt"
install_skill_copy "$TMPDIR/src" "$TMPDIR/dst/e" owner-e
test "$(marker_owner "$TMPDIR/dst/e/.agent-scripts-copy")" = "owner-e"
test ! -e "$TMPDIR/dst/e/.agent-scripts-copy-source"
test ! -e "$TMPDIR/dst/e/leftover.txt"

# Pre-marker generated copy (SKILL.md matches upstream): adopted.
mkdir -p "$TMPDIR/dst/f"
cp "$TMPDIR/src/SKILL.md" "$TMPDIR/dst/f/SKILL.md"
printf 'stale\n' > "$TMPDIR/dst/f/leftover.txt"
install_skill_copy "$TMPDIR/src" "$TMPDIR/dst/f" owner-f
test "$(marker_owner "$TMPDIR/dst/f/.agent-scripts-copy")" = "owner-f"
test ! -e "$TMPDIR/dst/f/leftover.txt"

# Marker-less dir whose SKILL.md differs from upstream: refused.
mkdir -p "$TMPDIR/dst/g"
printf 'my own skill\n' > "$TMPDIR/dst/g/SKILL.md"
if install_skill_copy "$TMPDIR/src" "$TMPDIR/dst/g" owner-g 2>/dev/null; then
  echo "FAIL: overwrote a dir with a diverging SKILL.md" >&2
  exit 1
fi
test "$(cat "$TMPDIR/dst/g/SKILL.md")" = "my own skill"

# Non-owned, non-empty directory: refused, content untouched.
mkdir -p "$TMPDIR/dst/c"
printf 'user content\n' > "$TMPDIR/dst/c/mine.txt"
if install_skill_copy "$TMPDIR/src" "$TMPDIR/dst/c" owner-c 2>/dev/null; then
  echo "FAIL: overwrote a non-owned directory" >&2
  exit 1
fi
test "$(cat "$TMPDIR/dst/c/mine.txt")" = "user content"
test ! -e "$TMPDIR/dst/c/SKILL.md"

# Plain file destination: refused.
printf 'f\n' > "$TMPDIR/dst/d"
if install_skill_copy "$TMPDIR/src" "$TMPDIR/dst/d" owner-d 2>/dev/null; then
  echo "FAIL: replaced a plain file" >&2
  exit 1
fi

# gitignore block regen: replaces its own block, leaves others alone.
GI="$TMPDIR/.gitignore"
printf '%s\n' 'keep1' '# foo start (generated by x)' 'skills/old' '# foo end' 'keep2' > "$GI"
regen_gitignore_block "$GI" "foo" "test" "skills/new"
grep -qx 'skills/new' "$GI"
! grep -qx 'skills/old' "$GI"
grep -qx 'keep1' "$GI"
grep -qx 'keep2' "$GI"

# Unterminated block: refuses to rewrite instead of eating to EOF.
printf '%s\n' '# foo start (generated by x)' 'skills/old' 'keep-tail' > "$GI"
if regen_gitignore_block "$GI" "foo" "test" "skills/new" 2>/dev/null; then
  echo "FAIL: rewrote an unterminated block" >&2
  exit 1
fi
grep -qx 'keep-tail' "$GI"

# ── Owner-keyed orphan cleanup ────────────────────────────────────────────
# Two owners share one surface AND one source_root. Each cleanup touches only
# the copies it owns — the exact cli-skills/matt-skills regression.
OWN="$TMPDIR/owners"
mkdir -p "$OWN/src/keep" "$OWN/src/gone" "$OWN/surface"
mk_copy() { # name owner
  mkdir -p "$OWN/surface/$1"
  printf '%s\n%s\n' "$OWN/src/$1" "$2" > "$OWN/surface/$1/.agent-scripts-copy"
}
mk_copy keep owner-x       # current for x
mk_copy gone owner-x       # orphan for x
mk_copy sibling owner-y    # owned by y, not in x's keep list

cleanup_marked_skill_copies "$OWN/surface" owner-x keep
test -d "$OWN/surface/keep"          # x keeps its current copy
test ! -e "$OWN/surface/gone"        # x removes its own orphan
test -d "$OWN/surface/sibling"       # y's copy survives without x knowing about it

# Empty current set: refuses to clean.
if cleanup_marked_skill_copies "$OWN/surface" owner-x 2>/dev/null; then
  echo "FAIL: cleaned against an empty current set" >&2
  exit 1
fi
test -d "$OWN/surface/keep"

# ── Legacy single-line markers are never deleted ──────────────────────────
# Pre-owner copies (source only, no owner line) can't be attributed when
# several updaters share a surface, so cleanup leaves them alone; each gets an
# owner line the next time its own updater re-syncs it.
LEG="$TMPDIR/legacy"
mkdir -p "$LEG/surface/legacy" "$LEG/surface/owned-gone"
printf '%s\n' "$LEG/src/legacy" > "$LEG/surface/legacy/.agent-scripts-copy"
printf '%s\n%s\n' "$LEG/src/owned-gone" owner-w > "$LEG/surface/owned-gone/.agent-scripts-copy"
cleanup_marked_skill_copies "$LEG/surface" owner-w keeper
test -d "$LEG/surface/legacy"        # unowned legacy copy survives
test ! -e "$LEG/surface/owned-gone"  # owner-stamped orphan is removed

# ── sync_skill_copies: the deepened recipe behind one interface ────────────
SY="$TMPDIR/sync"
mkdir -p "$SY/src/alpha" "$SY/src/beta" "$SY/surface"
printf '%s\n' '---' 'name: alpha' '---' > "$SY/src/alpha/SKILL.md"
printf '%s\n' '---' 'name: beta' '---'  > "$SY/src/beta/SKILL.md"
GI2="$SY/.gitignore"

# Happy path with a gitignore surface (Claude-style): copies installed with
# owner markers, block regenerated.
sync_skill_copies sync-owner "$SY/src" "$SY/surface" "$GI2" alpha beta
test -f "$SY/surface/alpha/SKILL.md"
test "$(marker_owner "$SY/surface/alpha/.agent-scripts-copy")" = "sync-owner"
grep -qx 'surface/alpha' "$GI2"
grep -qx 'surface/beta' "$GI2"

# Re-run dropping beta: orphan removed, block no longer lists it.
sync_skill_copies sync-owner "$SY/src" "$SY/surface" "$GI2" alpha
test -d "$SY/surface/alpha"
test ! -e "$SY/surface/beta"
grep -qx 'surface/alpha' "$GI2"
! grep -qx 'surface/beta' "$GI2"

# Codex-style surface (no gitignore): passes "" and never touches a file.
CX="$TMPDIR/codex"
mkdir -p "$CX/src/gamma" "$CX/surface"
printf '%s\n' '---' 'name: gamma' '---' > "$CX/src/gamma/SKILL.md"
sync_skill_copies cx-owner "$CX/src" "$CX/surface" "" gamma
test -f "$CX/surface/gamma/SKILL.md"
test "$(marker_owner "$CX/surface/gamma/.agent-scripts-copy")" = "cx-owner"

# Empty name list: refuses, returns non-zero, writes nothing.
EM="$TMPDIR/empty"
mkdir -p "$EM/src" "$EM/surface"
if sync_skill_copies em-owner "$EM/src" "$EM/surface" "" 2>/dev/null; then
  echo "FAIL: sync_skill_copies accepted an empty name list" >&2
  exit 1
fi

# Keep-ignoring-on-failure: a name whose source is gone but whose copy still
# exists on disk stays in the gitignore block and the call reports failure.
KF="$TMPDIR/keepfail"
mkdir -p "$KF/src/present" "$KF/surface/vanished"
printf '%s\n' '---' 'name: present' '---' > "$KF/src/present/SKILL.md"
printf '%s\n%s\n' "$KF/src/vanished" "kf-owner" > "$KF/surface/vanished/.agent-scripts-copy"
GI3="$KF/.gitignore"
if sync_skill_copies kf-owner "$KF/src" "$KF/surface" "$GI3" present vanished 2>/dev/null; then
  echo "FAIL: sync_skill_copies hid a missing source" >&2
  exit 1
fi
grep -qx 'surface/present' "$GI3"
grep -qx 'surface/vanished' "$GI3"   # copy on disk stays ignored despite the failure

echo "lib-copies tests passed"
