#!/usr/bin/env bash
set -euo pipefail

# Black-box test for scripts/update-khazix-skills.sh: run as a subprocess from a
# scratch repo with a stubbed git and a fake HOME; assert only on filesystem
# state and marker contents.

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TMPDIR="$(mktemp -d)"
trap 'rm -rf "$TMPDIR"' EXIT

FAKE_HOME="$TMPDIR/home"
REPO="$TMPDIR/repo"
CLONE="$FAKE_HOME/Projects/khazix-skills"
SKILLS="$REPO/skills"

mkdir -p "$REPO/scripts" "$SKILLS" "$CLONE/.git" "$CLONE/neat-freak" "$TMPDIR/bin"
cp "$REPO_ROOT/scripts/update-khazix-skills.sh" "$REPO_ROOT/scripts/lib-copies.sh" "$REPO/scripts/"
printf '%s\n' '---' 'name: neat-freak' 'description: "test"' '---' > "$CLONE/neat-freak/SKILL.md"

# neat-freak sits at the clone root (no skills/ subdir), so the clone dir is the
# source_root the updater passes to sync_skill_copies.
printf '%s\n' \
  '#!/usr/bin/env bash' \
  'case "$*" in' \
  '  *"pull --ff-only"*) exit 0 ;;' \
  '  *"clone "*) echo "unexpected clone" >&2; exit 1 ;;' \
  '  *) echo "unexpected git call: $*" >&2; exit 1 ;;' \
  'esac' > "$TMPDIR/bin/git"
chmod +x "$TMPDIR/bin/git"

# An owned orphan (khazix-skills) must be cleaned; a sibling owned by another
# updater and an unmarked hand-made dir must survive.
mkdir -p "$SKILLS/old-khazix" "$SKILLS/sibling" "$SKILLS/hand-made"
printf '%s\n%s\n' "$CLONE/old-khazix" khazix-skills > "$SKILLS/old-khazix/.agent-scripts-copy"
printf '%s\n%s\n' "$FAKE_HOME/.agents/skills/sibling" cli-skills > "$SKILLS/sibling/.agent-scripts-copy"
printf 'mine\n' > "$SKILLS/hand-made/SKILL.md"
printf '%s\n' \
  '# khazix-skills start (generated by sync_skill_copies)' \
  'skills/old-khazix' \
  '# khazix-skills end' > "$REPO/.gitignore"

run_sync() {
  HOME="$FAKE_HOME" PATH="$TMPDIR/bin:$PATH" AGENT_SCRIPTS_DISABLE_RSYNC=1 \
    "$REPO/scripts/update-khazix-skills.sh"
}

run_sync >/dev/null
run_sync >/dev/null # idempotent

test -f "$SKILLS/neat-freak/SKILL.md"
test "$(sed -n '1p' "$SKILLS/neat-freak/.agent-scripts-copy")" = "$CLONE/neat-freak"
test "$(sed -n '2p' "$SKILLS/neat-freak/.agent-scripts-copy")" = khazix-skills
grep -Fx 'skills/neat-freak' "$REPO/.gitignore" >/dev/null

test ! -e "$SKILLS/old-khazix"                       # owned orphan removed
! grep -Fx 'skills/old-khazix' "$REPO/.gitignore" >/dev/null
test -d "$SKILLS/sibling"                            # another owner's copy survives
test "$(cat "$SKILLS/hand-made/SKILL.md")" = "mine"  # unmarked dir untouched

echo "update-khazix-skills tests passed"
