#!/usr/bin/env bash
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SCRIPT="$REPO_ROOT/scripts/update-cli-skills.sh"

# skills@latest currently documents '*' for remove --agent, but rejects it.
if grep -Eq -- "--agent[[:space:]]+['\"]?\\*" "$SCRIPT"; then
  echo "FAIL: update-cli-skills.sh must not pass --agent '*' to skills remove" >&2
  exit 1
fi

grep -F 'SKILLS_CLI_AGENT=codex' "$SCRIPT" >/dev/null
grep -F 'run_skills remove $waza_list --global --agent "$SKILLS_CLI_AGENT" --yes' "$SCRIPT" >/dev/null

TMPDIR="$(mktemp -d)"
trap 'rm -rf "$TMPDIR"' EXIT

FAKE_HOME="$TMPDIR/home"
REPO="$TMPDIR/repo"
mkdir -p "$REPO/scripts" "$REPO/skills" "$FAKE_HOME/.agents/skills/find-skills" "$TMPDIR/bin"
cp "$REPO_ROOT/scripts/update-cli-skills.sh" "$REPO_ROOT/scripts/lib-copies.sh" "$REPO/scripts/"
printf '{"skills":{"find-skills":{"source":"vercel-labs/skills"}}}\n' > "$FAKE_HOME/.agents/.skill-lock.json"
printf '%s\n' '---' 'name: find-skills' 'description: "test"' '---' > "$FAKE_HOME/.agents/skills/find-skills/SKILL.md"

mkdir -p "$REPO/skills/old-cli" "$REPO/skills/matt-keep"
printf '%s\n%s\n' "$FAKE_HOME/.agents/skills/old-cli" cli-skills > "$REPO/skills/old-cli/.agent-scripts-copy"
printf '%s\n%s\n' "$FAKE_HOME/.agents/skills/matt-keep" matt-skills > "$REPO/skills/matt-keep/.agent-scripts-copy"
printf '%s\n' \
  '# cli-skills start (generated by update-cli-skills.sh)' \
  'skills/old-cli' \
  '# cli-skills end' \
  '# matt-skills start (generated by update-mattpocock-skills.sh)' \
  'skills/matt-keep' \
  '# matt-skills end' > "$REPO/.gitignore"

printf '%s\n' '#!/usr/bin/env bash' 'exit 0' > "$TMPDIR/bin/jq"
printf '%s\n' '#!/usr/bin/env bash' 'exit 0' > "$TMPDIR/bin/npx"
chmod +x "$TMPDIR/bin/jq" "$TMPDIR/bin/npx"

HOME="$FAKE_HOME" PATH="$TMPDIR/bin:$PATH" "$REPO/scripts/update-cli-skills.sh" >/dev/null
test -f "$REPO/skills/find-skills/SKILL.md"
test "$(sed -n '1p' "$REPO/skills/find-skills/.agent-scripts-copy")" = "$FAKE_HOME/.agents/skills/find-skills"
test "$(sed -n '2p' "$REPO/skills/find-skills/.agent-scripts-copy")" = cli-skills
test ! -e "$REPO/skills/old-cli"
test -d "$REPO/skills/matt-keep"
grep -Fx 'skills/find-skills' "$REPO/.gitignore" >/dev/null
! grep -Fx 'skills/old-cli' "$REPO/.gitignore" >/dev/null
grep -Fx 'skills/matt-keep' "$REPO/.gitignore" >/dev/null

echo "update-cli-skills tests passed"
