#!/usr/bin/env bash
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
REAL_GIT="$(command -v git)"
TMP_ROOT="$(mktemp -d)"
trap 'rm -rf "$TMP_ROOT"' EXIT

source "$REPO_ROOT/agent-tooling/lib-copies.sh"

make_skill() { # root name content
  local root="$1"
  local name="$2"
  local content="${3:-fixture}"
  mkdir -p "$root/$name"
  printf '%s\r\n' '---' "name: $name" 'description: "fixture"' '---' "$content" > "$root/$name/SKILL.md"
}

write_policy() { # fixture [extra override]
  local fixture="$1"
  local extra_override="${2:-}"
  cat > "$fixture/agent-tooling/skill-topology.json" <<JSON
{
  "version": 1,
  "sources": [
    {
      "id": "matt-skills",
      "classification": "npx-only",
      "defaultDestinations": ["codex"],
      "overrides": {
        "code-review": ["codex"]${extra_override}
      }
    }
  ]
}
JSON
  cat > "$fixture/agent-tooling/distribution-topology/registry.json" <<'JSON'
[
  {
    "sourceId": "matt-skills",
    "classification": "npx-only",
    "supportedDestinations": ["codex"],
    "command": "adapters/npx-source.sh",
    "stateInspection": "adapter",
    "matrixSource": "mattpocock/skills"
  }
]
JSON
}

make_fixture() { # fixture upstream
  local fixture="$1"
  local upstream="$2"

  mkdir -p "$fixture/agent-tooling" "$fixture/skills" "$fixture/other-skills/matt" \
    "$fixture/home/.agents/skills" "$fixture/home/.claude/skills" "$fixture/runtime" "$fixture/bin" \
    "$upstream/skills/engineering" "$upstream/skills/deprecated"
  printf 'claude-skills\n' > "$fixture/home/.claude/skills/.agent-scripts-root"
  cp "$REPO_ROOT/agent-tooling/update-skill-topology.sh" \
    "$REPO_ROOT/agent-tooling/sync-skill-surfaces.sh" \
    "$REPO_ROOT/agent-tooling/generate-skills-matrix.py" \
    "$REPO_ROOT/agent-tooling/lib-copies.sh" "$fixture/agent-tooling/"
  cp -R "$REPO_ROOT/agent-tooling/distribution-topology" "$fixture/agent-tooling/"
  git -C "$fixture" init -q

  make_skill "$upstream/skills/engineering" alpha upstream-alpha
  make_skill "$upstream/skills/engineering" code-review upstream-code-review
  make_skill "$upstream/skills/engineering" new-skill upstream-new

  # Marker-owned surface leftovers only — empty lock is the healthy baseline.
  make_skill "$fixture/home/.agents/skills" old-name installed-old-name
  make_skill "$fixture/home/.agents/skills" find-skills installed-find
  printf '%s\n' "$fixture/other-skills/matt/old-name" matt-skills hash > \
    "$fixture/home/.agents/skills/old-name/.agent-scripts-copy"
  printf '%s\n' "$fixture/other-skills/matt/find-skills" matt-skills hash > \
    "$fixture/home/.agents/skills/find-skills/.agent-scripts-copy"
  install_skill_copy "$fixture/home/.agents/skills/old-name" "$fixture/home/.claude/skills/old-name" matt-skills >/dev/null
  install_skill_copy "$fixture/home/.agents/skills/find-skills" "$fixture/home/.claude/skills/find-skills" cli-skills >/dev/null

  printf '%s\n' \
    '# cli-skills start (generated by update-cli-skills.sh)' \
    'skills/find-skills' \
    '# cli-skills end' > "$fixture/.gitignore"

  cat > "$fixture/home/.agents/.skill-lock.json" <<'JSON'
{
  "version": 3,
  "skills": {}
}
JSON
  perl -0pi -e 's/\n/\r\n/g' "$fixture/home/.agents/.skill-lock.json"

  cat > "$fixture/bin/git" <<'BASH'
#!/usr/bin/env bash
set -euo pipefail
if [ "${1:-}" = clone ]; then
  destination="${@: -1}"
  mkdir -p "$(dirname "$destination")"
  cp -R "$FAKE_MATT_UPSTREAM" "$destination"
  exit 0
fi
if [ "${1:-}" = -C ] && [ "${3:-}" = rev-parse ] && [ "${4:-}" = HEAD ]; then
  printf 'cccccccccccccccccccccccccccccccccccccccc\n'
  exit 0
fi
if [ "${1:-}" = -C ]; then
  exec "$REAL_GIT" "$@"
fi
printf 'unexpected git call: %s\n' "$*" >&2
exit 1
BASH

  # npx must never be invoked; any call fails the run and is logged.
  cat > "$fixture/bin/npx" <<'BASH'
#!/usr/bin/env bash
set -euo pipefail
printf '%s\n' "$*" >> "$FAKE_NPX_LOG"
printf 'npx skills CLI must not be invoked\n' >&2
exit 1
BASH
  chmod +x "$fixture/bin/git" "$fixture/bin/npx"
  : > "$fixture/npx.log"

  cat > "$fixture/agent-tooling/skills-matrix.md" <<'MD'
# Skills Matrix

| Skill | Source | Type | Claude | Codex |
| --- | --- | --- | --- | --- |
| `alpha` | mattpocock/skills | skill | N | Y |
| `code-review` | mattpocock/skills | skill | N | Y |
| `new-skill` | mattpocock/skills | skill | N | Y |
MD

  write_policy "$fixture"
}

enable_matt_plugin_fixture() { # fixture upstream
  local fixture="$1" upstream="$2"
  mkdir -p "$upstream/.claude-plugin"
  cat > "$upstream/.claude-plugin/marketplace.json" <<'JSON'
{"name":"mattpocock","plugins":[{"name":"mattpocock-skills","version":"1.0.0","source":"./"}]}
JSON
  jq '.sources += [{
    id: "matt-plugin",
    classification: "plugin-claude-only",
    defaultDestinations: ["claude"],
    overrides: {}
  }]' "$fixture/agent-tooling/skill-topology.json" > "$fixture/policy.tmp"
  mv "$fixture/policy.tmp" "$fixture/agent-tooling/skill-topology.json"
  jq '. += [{
    sourceId: "matt-plugin",
    classification: "plugin-claude-only",
    supportedDestinations: ["claude"],
    command: "adapters/plugin-both.sh",
    stateInspection: "adapter",
    plugin: {
      name: "mattpocock-skills",
      repo: "mattpocock/skills",
      marketplaces: {claude: "mattpocock"},
      skills: ["mattpocock-skills"]
    }
  }]' "$fixture/agent-tooling/distribution-topology/registry.json" > "$fixture/registry.tmp"
  mv "$fixture/registry.tmp" "$fixture/agent-tooling/distribution-topology/registry.json"
  printf '[]\n' > "$fixture/home/claude-plugins.json"
  printf '[]\n' > "$fixture/home/claude-marketplaces.json"

  cat > "$fixture/bin/claude" <<'BASH'
#!/usr/bin/env bash
set -euo pipefail
case "$*" in
  'plugin list --json') cat "$HOME/claude-plugins.json" ;;
  'plugin marketplace list --json') cat "$HOME/claude-marketplaces.json" ;;
  'plugin marketplace add mattpocock/skills')
    printf '[{"name":"mattpocock"}]\n' > "$HOME/claude-marketplaces.json"
    ;;
  'plugin install mattpocock-skills@mattpocock')
    mkdir -p "$HOME/plugin-roots/claude/mattpocock-skills/skills/ask-matt"
    printf '# Ask Matt\n' > "$HOME/plugin-roots/claude/mattpocock-skills/skills/ask-matt/SKILL.md"
    jq -n --arg path "$HOME/plugin-roots/claude/mattpocock-skills" \
      '[{id:"mattpocock-skills@mattpocock",version:"1.0.0",enabled:true,installPath:$path}]' \
      > "$HOME/claude-plugins.json"
    ;;
  *) printf 'unexpected claude call: %s\n' "$*" >&2; exit 1 ;;
esac
BASH
  cat > "$fixture/bin/codex" <<'BASH'
#!/usr/bin/env bash
set -euo pipefail
case "$*" in
  'plugin list --json') printf '{"installed":[]}\n' ;;
  *) printf 'unexpected codex call: %s\n' "$*" >&2; exit 1 ;;
esac
BASH
  chmod +x "$fixture/bin/claude" "$fixture/bin/codex"
}

run_phase() { # command fixture upstream output [extra env...]
  local command="$1"
  local fixture="$2"
  local upstream="$3"
  local output="$4"
  shift 4
  env "$@" REAL_GIT="$REAL_GIT" FAKE_MATT_UPSTREAM="$upstream" FAKE_NPX_LOG="$fixture/npx.log" \
    HOME="$fixture/home" TMPDIR="$fixture/runtime" PATH="$fixture/bin:$PATH" \
    "$fixture/agent-tooling/$command" --json > "$output"
}

run_acquire() { # fixture upstream output [extra env...]
  local fixture="$1"
  local upstream="$2"
  local output="$3"
  shift 3
  run_phase update-skill-topology.sh "$fixture" "$upstream" "$output" "$@"
}

run_distribute() { # fixture upstream output [extra env...]
  local fixture="$1"
  local upstream="$2"
  local output="$3"
  shift 3
  run_phase sync-skill-surfaces.sh "$fixture" "$upstream" "$output" "$@"
}

jq -e '
  (.sources[] | select(.id == "matt-skills") |
    .classification == "npx-only" and
    .defaultDestinations == ["codex"] and
    .overrides["code-review"] == ["codex"]) and
  (.sources[] | select(.id == "matt-plugin") |
    .classification == "plugin-claude-only" and
    .defaultDestinations == ["claude"]) and
  ([.sources[] | select(.id == "find-skills")] | length) == 0
' "$REPO_ROOT/agent-tooling/skill-topology.json" >/dev/null

FIXTURE="$TMP_ROOT/happy"
UPSTREAM="$TMP_ROOT/upstream"
make_fixture "$FIXTURE" "$UPSTREAM"
cp "$FIXTURE/home/.agents/.skill-lock.json" "$FIXTURE/lock-before.json"
run_acquire "$FIXTURE" "$UPSTREAM" "$FIXTURE/acquire.json"
jq -e '
  .status == "reconciled" and .errors == [] and .decisions == [] and
  all(.plan[] | select(.sourceId == "matt-skills"); .destinations == []) and
  ([.changes[] | select(.action == "installed" and .destination == "staging")] | length) == 3 and
  ([.changes[] | select(.destination == "claude" or .destination == "codex")] | length) == 0
' "$FIXTURE/acquire.json" >/dev/null
test -e "$FIXTURE/home/.agents/skills/old-name"
test -e "$FIXTURE/home/.claude/skills/old-name"
run_distribute "$FIXTURE" "$UPSTREAM" "$FIXTURE/first.json"
jq -e '
  .status == "reconciled" and .errors == [] and .decisions == [] and
  (.plan[] | select(.skill == "alpha") | .destinations == ["codex"]) and
  (.plan[] | select(.skill == "new-skill") | .destinations == ["codex"]) and
  (.plan[] | select(.skill == "code-review") | .destinations == ["codex"]) and
  ([.changes[] | select(.action == "removed" and .skill == "old-name")] | length) == 2 and
  ([.changes[] | select(.action == "removed" and .skill == "find-skills")] | length) == 2
' "$FIXTURE/first.json" >/dev/null
for skill in alpha code-review new-skill; do
  test -f "$FIXTURE/other-skills/matt/$skill/SKILL.md"
  test ! -e "$FIXTURE/other-skills/matt/$skill/.agent-scripts-copy"
  test ! -e "$FIXTURE/home/.claude/skills/$skill"
  test -f "$FIXTURE/home/.agents/skills/$skill/SKILL.md"
  test "$(sed -n '1p' "$FIXTURE/home/.agents/skills/$skill/.agent-scripts-copy")" = "$FIXTURE/other-skills/matt/$skill"
  test "$(sed -n '2p' "$FIXTURE/home/.agents/skills/$skill/.agent-scripts-copy")" = matt-skills
done
jq -e '
  .repo == "mattpocock/skills" and
  (.commit | type == "string" and length > 0) and
  (.syncedAt | type == "string" and length > 0)
' "$FIXTURE/other-skills/matt/.source.json" >/dev/null
if grep -F '# matt-skills ' "$FIXTURE/.gitignore" >/dev/null; then exit 1; fi
if grep -F 'other-skills/matt/' "$FIXTURE/.gitignore" >/dev/null; then exit 1; fi
test ! -e "$FIXTURE/home/.agents/skills/old-name"
test ! -e "$FIXTURE/home/.claude/skills/old-name"
test ! -e "$FIXTURE/home/.agents/skills/find-skills"
test ! -e "$FIXTURE/home/.claude/skills/find-skills"
if grep -F '# cli-skills ' "$FIXTURE/.gitignore" >/dev/null; then exit 1; fi
cmp -s "$FIXTURE/lock-before.json" "$FIXTURE/home/.agents/.skill-lock.json"
test ! -s "$FIXTURE/npx.log"

COMBINED="$TMP_ROOT/combined-matt"
COMBINED_UPSTREAM="$TMP_ROOT/combined-matt-upstream"
make_fixture "$COMBINED" "$COMBINED_UPSTREAM"
enable_matt_plugin_fixture "$COMBINED" "$COMBINED_UPSTREAM"
run_acquire "$COMBINED" "$COMBINED_UPSTREAM" "$COMBINED/acquire.json"
jq -e '
  .status == "reconciled" and .errors == [] and .decisions == [] and
  (.plan[] | select(.sourceId == "matt-plugin" and .skill == "mattpocock-skills") | .destinations == ["claude"]) and
  (.changes[] | select(.skill == "mattpocock-skills") | .action == "installed" and .destination == "claude") and
  (.changes[] | select(.skill == "alpha" and .destination == "staging") | .action == "installed")
' "$COMBINED/acquire.json" >/dev/null
run_distribute "$COMBINED" "$COMBINED_UPSTREAM" "$COMBINED/result.json"
jq -e '
  .status == "reconciled" and .errors == [] and .decisions == [] and
  (.plan[] | select(.sourceId == "matt-skills" and .skill == "alpha") | .destinations == ["codex"]) and
  (.changes[] | select(.skill == "alpha" and .destination == "codex") | .action == "installed")
' "$COMBINED/result.json" >/dev/null
test -f "$COMBINED/home/plugin-roots/claude/mattpocock-skills/skills/ask-matt/SKILL.md"
test -f "$COMBINED/other-skills/matt/alpha/SKILL.md"
test -f "$COMBINED/home/.agents/skills/alpha/SKILL.md"
test ! -e "$COMBINED/home/.claude/skills/alpha"
test ! -e "$COMBINED/home/.agents/skills/mattpocock-skills"

cp -R "$FIXTURE/home" "$FIXTURE/home-before-second"
cp -R "$FIXTURE/skills" "$FIXTURE/skills-before-second"
cp -R "$FIXTURE/other-skills" "$FIXTURE/other-skills-before-second"
: > "$FIXTURE/npx.log"
run_acquire "$FIXTURE" "$UPSTREAM" "$FIXTURE/second-acquire.json"
jq -e '(.status == "clean" or .status == "reconciled") and .changes == [] and .errors == [] and .decisions == []' \
  "$FIXTURE/second-acquire.json" >/dev/null
run_distribute "$FIXTURE" "$UPSTREAM" "$FIXTURE/second.json"
jq -e '(.status == "clean" or .status == "reconciled") and .changes == [] and .errors == [] and .decisions == []' \
  "$FIXTURE/second.json" >/dev/null
test ! -s "$FIXTURE/npx.log"
diff -r "$FIXTURE/home-before-second" "$FIXTURE/home"
diff -r "$FIXTURE/skills-before-second" "$FIXTURE/skills"
diff -r -x .source.json "$FIXTURE/other-skills-before-second" "$FIXTURE/other-skills"
jq -e '
  .repo == "mattpocock/skills" and
  (.commit | type == "string" and length > 0) and
  (.syncedAt | type == "string" and length > 0)
' "$FIXTURE/other-skills/matt/.source.json" >/dev/null

mv "$UPSTREAM/skills/engineering/new-skill" "$FIXTURE/new-skill.upstream-removed"
run_acquire "$FIXTURE" "$UPSTREAM" "$FIXTURE/staging-orphan.json"
jq -e '
  .status == "reconciled" and
  (.changes[] | .action == "removed" and .skill == "new-skill" and .destination == "staging")
' "$FIXTURE/staging-orphan.json" >/dev/null
test ! -e "$FIXTURE/other-skills/matt/new-skill"
test -e "$FIXTURE/home/.agents/skills/new-skill"
printf '%s\n' '# Skills Matrix' '' \
  '| Skill | Source | Type | Claude | Codex |' \
  '| --- | --- | --- | --- | --- |' \
  '| `alpha` | mattpocock/skills | skill | N | Y |' \
  '| `code-review` | mattpocock/skills | skill | N | Y |' \
  > "$FIXTURE/agent-tooling/skills-matrix.md"
run_distribute "$FIXTURE" "$UPSTREAM" "$FIXTURE/surface-orphan.json"
test ! -e "$FIXTURE/home/.agents/skills/new-skill"
test ! -s "$FIXTURE/npx.log"

KNOWN_LOCK="$TMP_ROOT/known-lock"
KNOWN_LOCK_UPSTREAM="$TMP_ROOT/known-lock-upstream"
make_fixture "$KNOWN_LOCK" "$KNOWN_LOCK_UPSTREAM"
cat > "$KNOWN_LOCK/home/.agents/.skill-lock.json" <<'JSON'
{
  "version": 3,
  "skills": {
    "alpha": {"source":"mattpocock/skills","sourceType":"github","skillPath":"skills/engineering/alpha/SKILL.md"},
    "old-name": {"source":"mattpocock/skills","sourceType":"github","skillPath":"skills/deprecated/old-name/SKILL.md"},
    "find-skills": {"source":"vercel-labs/skills","sourceType":"github","skillPath":"skills/find-skills/SKILL.md"}
  }
}
JSON
perl -0pi -e 's/\n/\r\n/g' "$KNOWN_LOCK/home/.agents/.skill-lock.json"
cp "$KNOWN_LOCK/home/.agents/.skill-lock.json" "$KNOWN_LOCK/lock-before.json"
cp -R "$KNOWN_LOCK/home" "$KNOWN_LOCK/home-before"
cp -R "$KNOWN_LOCK/skills" "$KNOWN_LOCK/skills-before"
cp -R "$KNOWN_LOCK/other-skills" "$KNOWN_LOCK/other-skills-before"
: > "$KNOWN_LOCK/npx.log"
set +e
run_acquire "$KNOWN_LOCK" "$KNOWN_LOCK_UPSTREAM" "$KNOWN_LOCK/result.json"
known_exit=$?
set -e
test "$known_exit" -eq 3
jq -e '
  .status == "decision-required" and .changes == [] and
  ([.decisions[] | select(.code == "legacy-npx-lock-entry")] | length) >= 1 and
  (.decisions[] | select(.code == "legacy-npx-lock-entry" and .skill == "alpha" and .lockSource == "mattpocock/skills")) and
  (.decisions[] | select(.code == "legacy-npx-lock-entry" and .skill == "old-name" and .lockSource == "mattpocock/skills")) and
  (.decisions[] | select(.code == "legacy-npx-lock-entry" and .skill == "find-skills" and .lockSource == "vercel-labs/skills"))
' "$KNOWN_LOCK/result.json" >/dev/null
test ! -s "$KNOWN_LOCK/npx.log"
cmp -s "$KNOWN_LOCK/lock-before.json" "$KNOWN_LOCK/home/.agents/.skill-lock.json"
diff -r "$KNOWN_LOCK/home-before" "$KNOWN_LOCK/home"
diff -r "$KNOWN_LOCK/skills-before" "$KNOWN_LOCK/skills"
diff -r "$KNOWN_LOCK/other-skills-before" "$KNOWN_LOCK/other-skills"

UNKNOWN="$TMP_ROOT/unknown"
UNKNOWN_UPSTREAM="$TMP_ROOT/unknown-upstream"
make_fixture "$UNKNOWN" "$UNKNOWN_UPSTREAM"
jq '.skills["other-skill"] = {source:"other/repo",sourceType:"github",skillPath:"skills/other-skill/SKILL.md"}' \
  "$UNKNOWN/home/.agents/.skill-lock.json" > "$UNKNOWN/lock.tmp"
mv "$UNKNOWN/lock.tmp" "$UNKNOWN/home/.agents/.skill-lock.json"
cp "$UNKNOWN/home/.agents/.skill-lock.json" "$UNKNOWN/lock-before.json"
: > "$UNKNOWN/npx.log"
cp -R "$UNKNOWN/home" "$UNKNOWN/home-before"
cp -R "$UNKNOWN/skills" "$UNKNOWN/skills-before"
cp -R "$UNKNOWN/other-skills" "$UNKNOWN/other-skills-before"
set +e
run_acquire "$UNKNOWN" "$UNKNOWN_UPSTREAM" "$UNKNOWN/result.json"
unknown_exit=$?
set -e
test "$unknown_exit" -eq 3
jq -e '
  .status == "decision-required" and .changes == [] and
  (.decisions[] | .code == "unknown-npx-lock-source" and .skill == "other-skill" and .lockSource == "other/repo")
' "$UNKNOWN/result.json" >/dev/null
test ! -s "$UNKNOWN/npx.log"
cmp -s "$UNKNOWN/lock-before.json" "$UNKNOWN/home/.agents/.skill-lock.json"
diff -r "$UNKNOWN/home-before" "$UNKNOWN/home"
diff -r "$UNKNOWN/skills-before" "$UNKNOWN/skills"
diff -r "$UNKNOWN/other-skills-before" "$UNKNOWN/other-skills"

STALE="$TMP_ROOT/stale"
STALE_UPSTREAM="$TMP_ROOT/stale-upstream"
make_fixture "$STALE" "$STALE_UPSTREAM"
write_policy "$STALE" ', "renamed-skill": ["codex"]'
jq '.[0] |= del(.matrixSource)' "$STALE/agent-tooling/distribution-topology/registry.json" \
  > "$STALE/registry.tmp"
mv "$STALE/registry.tmp" "$STALE/agent-tooling/distribution-topology/registry.json"
: > "$STALE/npx.log"
run_acquire "$STALE" "$STALE_UPSTREAM" "$STALE/acquire.json"
set +e
run_distribute "$STALE" "$STALE_UPSTREAM" "$STALE/result.json"
stale_exit=$?
set -e
test "$stale_exit" -eq 3
jq -e '.status == "decision-required" and .changes == [] and (.decisions[] | .code == "stale-override" and .skill == "renamed-skill")' \
  "$STALE/result.json" >/dev/null
test ! -s "$STALE/npx.log"

COLLISION="$TMP_ROOT/collision"
COLLISION_UPSTREAM="$TMP_ROOT/collision-upstream"
make_fixture "$COLLISION" "$COLLISION_UPSTREAM"
make_skill "$COLLISION/home/.agents/skills" alpha installed-old-alpha
: > "$COLLISION/npx.log"
run_acquire "$COLLISION" "$COLLISION_UPSTREAM" "$COLLISION/acquire.json"
set +e
run_distribute "$COLLISION" "$COLLISION_UPSTREAM" "$COLLISION/result.json"
collision_exit=$?
set -e
test "$collision_exit" -eq 3
jq -e '.status == "decision-required" and (.decisions[] | .code == "surface-ownership-collision" and .skill == "alpha" and .destination == "codex")' \
  "$COLLISION/result.json" >/dev/null
test ! -s "$COLLISION/npx.log"

DIRECT_STAGE="$TMP_ROOT/direct-stage"
DIRECT_STAGE_UPSTREAM="$TMP_ROOT/direct-stage-upstream"
make_fixture "$DIRECT_STAGE" "$DIRECT_STAGE_UPSTREAM"
: > "$DIRECT_STAGE/npx.log"
run_acquire "$DIRECT_STAGE" "$DIRECT_STAGE_UPSTREAM" "$DIRECT_STAGE/result.json"
jq -e '.status == "reconciled" and .errors == []' "$DIRECT_STAGE/result.json" >/dev/null
test -f "$DIRECT_STAGE/other-skills/matt/new-skill/SKILL.md"
test ! -s "$DIRECT_STAGE/npx.log"

echo "npx-distributed topology tests passed"
