#!/usr/bin/env bash
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TMPDIR="$(mktemp -d)"
trap 'rm -rf "$TMPDIR"' EXIT

FAKE_HOME="$TMPDIR/home"
REPO="$TMPDIR/repo"

mkdir -p "$REPO/scripts" "$REPO/skills" "$FAKE_HOME/.agents/skills" "$TMPDIR/bin"
cp "$REPO_ROOT/scripts/update-mattpocock-skills.sh" "$REPO_ROOT/scripts/lib-copies.sh" "$REPO/scripts/"

make_source() { # name
  mkdir -p "$FAKE_HOME/.agents/skills/$1"
  printf '%s\n' '---' "name: $1" 'description: "test"' '---' > "$FAKE_HOME/.agents/skills/$1/SKILL.md"
}

make_marked_copy() { # name source_name owner
  mkdir -p "$REPO/skills/$1"
  printf '%s\n%s\n' "$FAKE_HOME/.agents/skills/$2" "$3" > "$REPO/skills/$1/.agent-scripts-copy"
  printf 'stale\n' > "$REPO/skills/$1/SKILL.md"
}

printf '%s\n' \
  '#!/usr/bin/env bash' \
  'if grep -q "\"empty\":true" "$HOME/.agents/.skill-lock.json"; then exit 0; fi' \
  'printf "%s\n" "$*" >> "$HOME/npx-args"' \
  'if [[ " $* " == *" remove "* ]]; then' \
  '  : # Real CLI can return success without cleaning lock entries or directories.' \
  'else' \
  '  mkdir -p "$HOME/.agents/skills/gamma"' \
  '  printf "%s\n" "---" "name: gamma" "description: test" "---" > "$HOME/.agents/skills/gamma/SKILL.md"' \
  '  printf '\''{"skills":{"alpha":"mattpocock/skills","beta":"mattpocock/skills","old-name":"mattpocock/skills","gamma":"mattpocock/skills","code-review":"mattpocock/skills"}}\n'\'' > "$HOME/.agents/.skill-lock.json"' \
  'fi' \
  'exit 0' > "$TMPDIR/bin/npx"
printf '%s\n' \
  '#!/usr/bin/env bash' \
  'dest="${@: -1}"' \
  'for name in alpha gamma code-review; do' \
  '  mkdir -p "$dest/skills/test/$name"' \
  '  printf "%s\n" "---" "name: $name" "---" > "$dest/skills/test/$name/SKILL.md"' \
  'done' > "$TMPDIR/bin/git"
chmod +x "$TMPDIR/bin/npx" "$TMPDIR/bin/git"

make_source alpha
make_source beta
make_source code-review
make_source old-name
printf '{"skills":{"alpha":"mattpocock/skills","beta":"mattpocock/skills","old-name":"mattpocock/skills","code-review":"mattpocock/skills"}}\n' > "$FAKE_HOME/.agents/.skill-lock.json"
make_marked_copy old-name old-name matt-skills
make_marked_copy old-matt old-matt matt-skills
make_marked_copy find-skills find-skills cli-skills
printf '%s\n' \
  '# cli-skills start (generated by update-cli-skills.sh)' \
  'skills/find-skills' \
  '# cli-skills end' \
  '# matt-skills start (generated by update-mattpocock-skills.sh)' \
  'skills/old-matt' \
  '# matt-skills end' > "$REPO/.gitignore"

HOME="$FAKE_HOME" PATH="$TMPDIR/bin:$PATH" "$REPO/scripts/update-mattpocock-skills.sh" >/dev/null
test -f "$REPO/skills/alpha/SKILL.md"
test -f "$REPO/skills/gamma/SKILL.md"
test ! -e "$FAKE_HOME/.agents/skills/beta"
test ! -e "$FAKE_HOME/.agents/skills/old-name"
jq -e '.skills.beta == null and .skills["old-name"] == null' "$FAKE_HOME/.agents/.skill-lock.json" >/dev/null
test ! -e "$REPO/skills/beta"
test ! -e "$REPO/skills/old-name"
test ! -e "$REPO/skills/code-review"
test ! -e "$REPO/skills/old-matt"
test -d "$REPO/skills/find-skills"
grep -Fx 'skills/alpha' "$REPO/.gitignore" >/dev/null
grep -Fx 'skills/gamma' "$REPO/.gitignore" >/dev/null
grep -F 'add mattpocock/skills --skill * --agent codex --global --yes' "$FAKE_HOME/npx-args" >/dev/null
grep -F 'remove beta old-name --global --agent codex --yes' "$FAKE_HOME/npx-args" >/dev/null
! grep -Fx 'skills/old-matt' "$REPO/.gitignore" >/dev/null
grep -Fx 'skills/find-skills' "$REPO/.gitignore" >/dev/null

make_marked_copy old-empty old-empty matt-skills
printf '{"empty":true,"skills":{}}\n' > "$FAKE_HOME/.agents/.skill-lock.json"
printf '%s\n' \
  '# matt-skills start (generated by update-mattpocock-skills.sh)' \
  'skills/old-empty' \
  '# matt-skills end' > "$REPO/.gitignore"
if HOME="$FAKE_HOME" PATH="$TMPDIR/bin:$PATH" "$REPO/scripts/update-mattpocock-skills.sh" >/dev/null 2>&1; then
  echo "FAIL: ran cleanup against an empty mattpocock enumeration" >&2
  exit 1
fi
test -d "$REPO/skills/old-empty"
grep -Fx 'skills/old-empty' "$REPO/.gitignore" >/dev/null

printf '{"skills":{"../../escape":"mattpocock/skills"}}\n' > "$FAKE_HOME/.agents/.skill-lock.json"
: > "$FAKE_HOME/npx-args"
if HOME="$FAKE_HOME" PATH="$TMPDIR/bin:$PATH" "$REPO/scripts/update-mattpocock-skills.sh" >/dev/null 2>&1; then
  echo "FAIL: accepted an unsafe lock key" >&2
  exit 1
fi
test ! -s "$FAKE_HOME/npx-args"

echo "update-mattpocock-skills tests passed"
