#!/usr/bin/env bash
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TMPDIR="$(mktemp -d)"
trap 'rm -rf "$TMPDIR"' EXIT

FAKE_HOME="$TMPDIR/home"
REPO="$TMPDIR/repo"

mkdir -p "$REPO/scripts" "$REPO/skills" "$FAKE_HOME/.agents/skills" "$TMPDIR/bin"
cp "$REPO_ROOT/scripts/update-mattpocock-skills.sh" "$REPO_ROOT/scripts/lib-copies.sh" "$REPO/scripts/"

make_source() { # name
  mkdir -p "$FAKE_HOME/.agents/skills/$1"
  printf '%s\n' '---' "name: $1" 'description: "test"' '---' > "$FAKE_HOME/.agents/skills/$1/SKILL.md"
}

make_marked_copy() { # name source_name owner
  mkdir -p "$REPO/skills/$1"
  printf '%s\n%s\n' "$FAKE_HOME/.agents/skills/$2" "$3" > "$REPO/skills/$1/.agent-scripts-copy"
  printf 'stale\n' > "$REPO/skills/$1/SKILL.md"
}

printf '%s\n' \
  '#!/usr/bin/env bash' \
  'lock="${@: -1}"' \
  'if grep -q "\"empty\":true" "$lock"; then' \
  '  exit 0' \
  'fi' \
  'if grep -q mattpocock/skills "$lock"; then' \
  '  printf "%s\n" alpha beta code-review' \
  'fi' > "$TMPDIR/bin/jq"
printf '%s\n' '#!/usr/bin/env bash' 'echo "unexpected npx call" >&2' 'exit 1' > "$TMPDIR/bin/npx"
chmod +x "$TMPDIR/bin/jq" "$TMPDIR/bin/npx"

make_source alpha
make_source beta
make_source code-review
printf '{"skills":{"alpha":"mattpocock/skills","beta":"mattpocock/skills","code-review":"mattpocock/skills"}}\n' > "$FAKE_HOME/.agents/.skill-lock.json"
make_marked_copy old-matt old-matt matt-skills
make_marked_copy find-skills find-skills cli-skills
printf '%s\n' \
  '# cli-skills start (generated by update-cli-skills.sh)' \
  'skills/find-skills' \
  '# cli-skills end' \
  '# matt-skills start (generated by update-mattpocock-skills.sh)' \
  'skills/old-matt' \
  '# matt-skills end' > "$REPO/.gitignore"

HOME="$FAKE_HOME" PATH="$TMPDIR/bin:$PATH" "$REPO/scripts/update-mattpocock-skills.sh" >/dev/null
test -f "$REPO/skills/alpha/SKILL.md"
test -f "$REPO/skills/beta/SKILL.md"
test ! -e "$REPO/skills/code-review"
test ! -e "$REPO/skills/old-matt"
test -d "$REPO/skills/find-skills"
grep -Fx 'skills/alpha' "$REPO/.gitignore" >/dev/null
grep -Fx 'skills/beta' "$REPO/.gitignore" >/dev/null
! grep -Fx 'skills/old-matt' "$REPO/.gitignore" >/dev/null
grep -Fx 'skills/find-skills' "$REPO/.gitignore" >/dev/null

make_marked_copy old-empty old-empty matt-skills
printf '{"empty":true,"skills":{"ghost":"mattpocock/skills"}}\n' > "$FAKE_HOME/.agents/.skill-lock.json"
printf '%s\n' \
  '# matt-skills start (generated by update-mattpocock-skills.sh)' \
  'skills/old-empty' \
  '# matt-skills end' > "$REPO/.gitignore"
if HOME="$FAKE_HOME" PATH="$TMPDIR/bin:$PATH" "$REPO/scripts/update-mattpocock-skills.sh" >/dev/null 2>&1; then
  echo "FAIL: ran cleanup against an empty mattpocock enumeration" >&2
  exit 1
fi
test -d "$REPO/skills/old-empty"
grep -Fx 'skills/old-empty' "$REPO/.gitignore" >/dev/null

echo "update-mattpocock-skills tests passed"
