#!/usr/bin/env bash
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TMPDIR="$(mktemp -d)"
trap 'rm -rf "$TMPDIR"' EXIT

FAKE_HOME="$TMPDIR/home"
REPO="$TMPDIR/repo"
CLONE="$FAKE_HOME/Projects/anthropic-skills"
CODEX_SURFACE="$FAKE_HOME/.agents/skills"

mkdir -p "$REPO/scripts" "$REPO/skills" "$CLONE/skills" "$CLONE/.git" "$CODEX_SURFACE" "$TMPDIR/bin"
cp "$REPO_ROOT/scripts/update-anthropic-skills.sh" "$REPO_ROOT/scripts/lib-copies.sh" "$REPO/scripts/"

make_source() { # name
  mkdir -p "$CLONE/skills/$1"
  printf '%s\n' '---' "name: $1" 'description: "test"' '---' > "$CLONE/skills/$1/SKILL.md"
}

make_marked_copy() { # surface name source_name
  mkdir -p "$1/$2"
  printf '%s\n' "$CLONE/skills/$3" > "$1/$2/.agent-scripts-copy"
  printf 'stale\n' > "$1/$2/SKILL.md"
}

for skill in docx xlsx pdf pptx frontend-design skill-creator; do
  make_source "$skill"
done

make_marked_copy "$REPO/skills" old-doc old-doc
make_marked_copy "$CODEX_SURFACE" old-doc old-doc
mkdir -p "$REPO/skills/hand-made" "$CODEX_SURFACE/hand-made"
printf 'mine\n' > "$REPO/skills/hand-made/SKILL.md"
printf 'mine\n' > "$CODEX_SURFACE/hand-made/SKILL.md"
printf '%s\n' \
  '# anthropic-skills start (generated by update-anthropic-skills.sh)' \
  'skills/old-doc' \
  '# anthropic-skills end' > "$REPO/.gitignore"

printf '%s\n' \
  '#!/usr/bin/env bash' \
  'case "$*" in' \
  '  *"pull --ff-only"*) exit 0 ;;' \
  '  *"clone "*) echo "unexpected clone" >&2; exit 1 ;;' \
  '  *) echo "unexpected git call: $*" >&2; exit 1 ;;' \
  'esac' > "$TMPDIR/bin/git"
chmod +x "$TMPDIR/bin/git"

run_sync() {
  HOME="$FAKE_HOME" PATH="$TMPDIR/bin:$PATH" AGENT_SCRIPTS_DISABLE_RSYNC=1 \
    "$REPO/scripts/update-anthropic-skills.sh"
}

run_sync >/dev/null
run_sync >/dev/null

for skill in docx xlsx pdf pptx; do
  test -f "$REPO/skills/$skill/SKILL.md"
  test "$(cat "$REPO/skills/$skill/.agent-scripts-copy")" = "$CLONE/skills/$skill"
  test -f "$CODEX_SURFACE/$skill/SKILL.md"
  test "$(cat "$CODEX_SURFACE/$skill/.agent-scripts-copy")" = "$CLONE/skills/$skill"
  grep -Fx "skills/$skill" "$REPO/.gitignore" >/dev/null
done

for skill in frontend-design skill-creator; do
  test ! -e "$REPO/skills/$skill"
  test -f "$CODEX_SURFACE/$skill/SKILL.md"
  test "$(cat "$CODEX_SURFACE/$skill/.agent-scripts-copy")" = "$CLONE/skills/$skill"
done

test ! -e "$REPO/skills/old-doc"
test ! -e "$CODEX_SURFACE/old-doc"
! grep -Fx 'skills/old-doc' "$REPO/.gitignore" >/dev/null
test "$(cat "$REPO/skills/hand-made/SKILL.md")" = "mine"
test "$(cat "$CODEX_SURFACE/hand-made/SKILL.md")" = "mine"

echo "update-anthropic-skills tests passed"
