#!/usr/bin/env bash
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
REAL_GIT="$(command -v git)"
TMP_ROOT="$(mktemp -d)"
trap 'rm -rf "$TMP_ROOT"' EXIT

source "$REPO_ROOT/scripts/lib-copies.sh"

make_skill() { # root name content
  local root="$1"
  local name="$2"
  local content="${3:-fixture}"
  mkdir -p "$root/$name"
  printf '%s\r\n' '---' "name: $name" 'description: "fixture"' '---' "$content" > "$root/$name/SKILL.md"
}

write_policy() { # fixture [extra override]
  local fixture="$1"
  local extra_override="${2:-}"
  cat > "$fixture/skill-topology.json" <<JSON
{
  "version": 1,
  "sources": [
    {
      "id": "matt-skills",
      "classification": "npx-only",
      "defaultDestinations": ["claude", "codex"],
      "overrides": {
        "code-review": ["codex"]${extra_override}
      }
    }
  ]
}
JSON
  cat > "$fixture/scripts/distribution-topology/registry.json" <<'JSON'
[
  {
    "sourceId": "matt-skills",
    "classification": "npx-only",
    "supportedDestinations": ["claude", "codex"],
    "command": "adapters/npx-source.sh",
    "stateInspection": "adapter"
  }
]
JSON
}

make_fixture() { # fixture upstream
  local fixture="$1"
  local upstream="$2"
  local old_source

  mkdir -p "$fixture/scripts" "$fixture/skills" "$fixture/other-skills/matt" \
    "$fixture/home/.agents/skills" "$fixture/runtime" "$fixture/bin" \
    "$upstream/skills/engineering" "$upstream/skills/deprecated"
  cp "$REPO_ROOT/scripts/update-skill-topology.sh" "$REPO_ROOT/scripts/lib-copies.sh" "$fixture/scripts/"
  cp -R "$REPO_ROOT/scripts/distribution-topology" "$fixture/scripts/"
  git -C "$fixture" init -q

  make_skill "$upstream/skills/engineering" alpha upstream-alpha
  make_skill "$upstream/skills/engineering" code-review upstream-code-review
  make_skill "$upstream/skills/engineering" new-skill upstream-new

  make_skill "$fixture/home/.agents/skills" alpha installed-old-alpha
  make_skill "$fixture/home/.agents/skills" old-name installed-old-name
  make_skill "$fixture/home/.agents/skills" find-skills installed-find

  install_skill_copy "$fixture/home/.agents/skills/alpha" "$fixture/skills/alpha" matt-skills >/dev/null
  install_skill_copy "$fixture/home/.agents/skills/old-name" "$fixture/skills/old-name" matt-skills >/dev/null
  install_skill_copy "$fixture/home/.agents/skills/find-skills" "$fixture/skills/find-skills" cli-skills >/dev/null

  printf '%s\n' \
    '# cli-skills start (generated by update-cli-skills.sh)' \
    'skills/find-skills' \
    '# cli-skills end' > "$fixture/.gitignore"

  cat > "$fixture/home/.agents/.skill-lock.json" <<'JSON'
{
  "version": 3,
  "skills": {
    "alpha": {"source":"mattpocock/skills","sourceType":"github","skillPath":"skills/engineering/alpha/SKILL.md"},
    "old-name": {"source":"mattpocock/skills","sourceType":"github","skillPath":"skills/deprecated/old-name/SKILL.md"},
    "find-skills": {"source":"vercel-labs/skills","sourceType":"github","skillPath":"skills/find-skills/SKILL.md"}
  }
}
JSON
  perl -0pi -e 's/\n/\r\n/g' "$fixture/home/.agents/.skill-lock.json"

  cat > "$fixture/bin/git" <<'BASH'
#!/usr/bin/env bash
set -euo pipefail
if [ "${1:-}" = clone ]; then
  destination="${@: -1}"
  mkdir -p "$(dirname "$destination")"
  cp -R "$FAKE_MATT_UPSTREAM" "$destination"
  exit 0
fi
if [ "${1:-}" = -C ]; then
  exec "$REAL_GIT" "$@"
fi
printf 'unexpected git call: %s\n' "$*" >&2
exit 1
BASH

  cat > "$fixture/bin/npx" <<'BASH'
#!/usr/bin/env bash
set -euo pipefail
printf '%s\n' "$*" >> "$FAKE_NPX_LOG"
[ "${1:-}" = --yes ] && shift
[ "${1:-}" = skills@latest ] && shift
command="${1:-}"
shift || true

update_lock_entry() {
  local name="$1"
  local skill_path="$2"
  local tmp="$HOME/.agents/.skill-lock.json.tmp"
  jq --arg name "$name" --arg skill_path "$skill_path" \
    '.skills[$name] = {source:"mattpocock/skills", sourceType:"github", skillPath:$skill_path}' \
    "$HOME/.agents/.skill-lock.json" > "$tmp"
  mv "$tmp" "$HOME/.agents/.skill-lock.json"
}

case "$command" in
  add)
    count=0
    while IFS= read -r skill_file; do
      source_dir="$(dirname "$skill_file")"
      name="$(basename "$source_dir")"
      rm -rf "$HOME/.agents/skills/$name"
      cp -R "$source_dir" "$HOME/.agents/skills/$name"
      skill_path="${skill_file#"$FAKE_MATT_UPSTREAM/"}"
      update_lock_entry "$name" "$skill_path"
      count=$((count + 1))
      if [ "${FAKE_NPX_PARTIAL:-0}" = 1 ] && [ "$count" -eq 1 ]; then
        printf 'Failed to install remaining skills\r\n'
        exit 0
      fi
    done < <(find "$FAKE_MATT_UPSTREAM/skills" -name SKILL.md | LC_ALL=C sort)
    ;;
  remove)
    names=()
    while [ "$#" -gt 0 ] && [ "$1" != --global ]; do
      names+=("$1")
      shift
    done
    for name in "${names[@]}"; do
      rm -rf "$HOME/.agents/skills/$name"
      tmp="$HOME/.agents/.skill-lock.json.tmp"
      jq --arg name "$name" 'del(.skills[$name])' "$HOME/.agents/.skill-lock.json" > "$tmp"
      mv "$tmp" "$HOME/.agents/.skill-lock.json"
    done
    ;;
  *) printf 'unexpected npx command: %s\n' "$command" >&2; exit 1 ;;
esac
BASH
  chmod +x "$fixture/bin/git" "$fixture/bin/npx"

  write_policy "$fixture"
  old_source="$fixture/home/.agents/skills/old-name"
  test "$(sed -n '1p' "$fixture/skills/old-name/.agent-scripts-copy")" = "$old_source"
}

run_topology() { # fixture upstream output [extra env...]
  local fixture="$1"
  local upstream="$2"
  local output="$3"
  shift 3
  env "$@" REAL_GIT="$REAL_GIT" FAKE_MATT_UPSTREAM="$upstream" FAKE_NPX_LOG="$fixture/npx.log" \
    HOME="$fixture/home" TMPDIR="$fixture/runtime" PATH="$fixture/bin:$PATH" \
    "$fixture/scripts/update-skill-topology.sh" --json > "$output"
}

jq -e '
  (.sources[] | select(.id == "matt-skills") |
    .classification == "npx-only" and
    .defaultDestinations == ["codex"] and
    .overrides["code-review"] == ["codex"]) and
  (.sources[] | select(.id == "matt-plugin") |
    .classification == "plugin-claude-only" and
    .defaultDestinations == ["claude"]) and
  ([.sources[] | select(.id == "find-skills")] | length) == 0
' "$REPO_ROOT/skill-topology.json" >/dev/null

FIXTURE="$TMP_ROOT/happy"
UPSTREAM="$TMP_ROOT/upstream"
make_fixture "$FIXTURE" "$UPSTREAM"
run_topology "$FIXTURE" "$UPSTREAM" "$FIXTURE/first.json"
jq -e '
  .status == "reconciled" and .errors == [] and .decisions == [] and
  (.plan[] | select(.skill == "alpha") | .destinations == ["claude", "codex"]) and
  (.plan[] | select(.skill == "new-skill") | .destinations == ["claude", "codex"]) and
  (.plan[] | select(.skill == "code-review") | .destinations == ["codex"]) and
  ([.changes[] | select(.action == "removed" and .skill == "old-name")] | length) == 2 and
  ([.changes[] | select(.action == "removed" and .skill == "find-skills")] | length) == 2
' "$FIXTURE/first.json" >/dev/null
for skill in alpha code-review new-skill; do
  test -f "$FIXTURE/other-skills/matt/$skill/SKILL.md"
  test "$(sed -n '2p' "$FIXTURE/other-skills/matt/$skill/.agent-scripts-copy")" = matt-skills
  test ! -e "$FIXTURE/skills/$skill"
  test ! -e "$FIXTURE/home/.agents/skills/$skill"
done
grep -F '# matt-skills start (generated by update-skill-topology.sh)' "$FIXTURE/.gitignore" >/dev/null
grep -Fx 'other-skills/matt/new-skill' "$FIXTURE/.gitignore" >/dev/null
test ! -e "$FIXTURE/home/.agents/skills/old-name"
test ! -e "$FIXTURE/skills/old-name"
test ! -e "$FIXTURE/home/.agents/skills/find-skills"
test ! -e "$FIXTURE/skills/find-skills"
if grep -F '# cli-skills ' "$FIXTURE/.gitignore" >/dev/null; then exit 1; fi
jq -e '.skills | has("old-name") | not' "$FIXTURE/home/.agents/.skill-lock.json" >/dev/null
jq -e '.skills | has("find-skills") | not' "$FIXTURE/home/.agents/.skill-lock.json" >/dev/null
if grep -F 'add mattpocock/skills' "$FIXTURE/npx.log" >/dev/null; then exit 1; fi
grep -F 'remove alpha old-name find-skills --global --agent codex --yes' "$FIXTURE/npx.log" >/dev/null
if grep -F ' update ' "$FIXTURE/npx.log" >/dev/null; then exit 1; fi

cp -R "$FIXTURE/home" "$FIXTURE/home-before-second"
cp -R "$FIXTURE/skills" "$FIXTURE/skills-before-second"
cp -R "$FIXTURE/other-skills" "$FIXTURE/other-skills-before-second"
: > "$FIXTURE/npx.log"
run_topology "$FIXTURE" "$UPSTREAM" "$FIXTURE/second.json"
jq -e '.status == "reconciled" and .changes == [] and .errors == [] and .decisions == []' "$FIXTURE/second.json" >/dev/null
test ! -s "$FIXTURE/npx.log"
diff -r "$FIXTURE/home-before-second" "$FIXTURE/home"
diff -r "$FIXTURE/skills-before-second" "$FIXTURE/skills"
diff -r "$FIXTURE/other-skills-before-second" "$FIXTURE/other-skills"

mv "$UPSTREAM/skills/engineering/new-skill" "$FIXTURE/new-skill.upstream-removed"
run_topology "$FIXTURE" "$UPSTREAM" "$FIXTURE/staging-orphan.json"
jq -e '
  .status == "reconciled" and
  (.changes[] | .action == "removed" and .skill == "new-skill")
' "$FIXTURE/staging-orphan.json" >/dev/null
test ! -e "$FIXTURE/other-skills/matt/new-skill"
if grep -F 'add mattpocock/skills' "$FIXTURE/npx.log" >/dev/null; then exit 1; fi

UNKNOWN="$TMP_ROOT/unknown"
UNKNOWN_UPSTREAM="$TMP_ROOT/unknown-upstream"
make_fixture "$UNKNOWN" "$UNKNOWN_UPSTREAM"
jq '.skills["other-skill"] = {source:"other/repo",sourceType:"github",skillPath:"skills/other-skill/SKILL.md"}' \
  "$UNKNOWN/home/.agents/.skill-lock.json" > "$UNKNOWN/lock.tmp"
mv "$UNKNOWN/lock.tmp" "$UNKNOWN/home/.agents/.skill-lock.json"
: > "$UNKNOWN/npx.log"
cp -R "$UNKNOWN/home" "$UNKNOWN/home-before"
cp -R "$UNKNOWN/skills" "$UNKNOWN/skills-before"
cp -R "$UNKNOWN/other-skills" "$UNKNOWN/other-skills-before"
set +e
run_topology "$UNKNOWN" "$UNKNOWN_UPSTREAM" "$UNKNOWN/result.json"
unknown_exit=$?
set -e
test "$unknown_exit" -eq 3
jq -e '
  .status == "decision-required" and .changes == [] and
  (.decisions[] | .code == "unknown-npx-lock-source" and .skill == "other-skill" and .lockSource == "other/repo")
' "$UNKNOWN/result.json" >/dev/null
test ! -s "$UNKNOWN/npx.log"
diff -r "$UNKNOWN/home-before" "$UNKNOWN/home"
diff -r "$UNKNOWN/skills-before" "$UNKNOWN/skills"
diff -r "$UNKNOWN/other-skills-before" "$UNKNOWN/other-skills"

STALE="$TMP_ROOT/stale"
STALE_UPSTREAM="$TMP_ROOT/stale-upstream"
make_fixture "$STALE" "$STALE_UPSTREAM"
write_policy "$STALE" ', "renamed-skill": ["codex"]'
: > "$STALE/npx.log"
set +e
run_topology "$STALE" "$STALE_UPSTREAM" "$STALE/result.json"
stale_exit=$?
set -e
test "$stale_exit" -eq 3
jq -e '.status == "decision-required" and .changes == [] and (.decisions[] | .code == "stale-override" and .skill == "renamed-skill")' \
  "$STALE/result.json" >/dev/null
test ! -s "$STALE/npx.log"

COLLISION="$TMP_ROOT/collision"
COLLISION_UPSTREAM="$TMP_ROOT/collision-upstream"
make_fixture "$COLLISION" "$COLLISION_UPSTREAM"
mkdir -p "$COLLISION/skills/alpha"
cp "$COLLISION_UPSTREAM/skills/engineering/alpha/SKILL.md" "$COLLISION/skills/alpha/SKILL.md"
git -C "$COLLISION" add skills/alpha/SKILL.md
jq '.sources += [{id:"repo-claude",classification:"repo-owned",defaultDestinations:["claude"],overrides:{}}]' \
  "$COLLISION/skill-topology.json" > "$COLLISION/manifest.tmp"
mv "$COLLISION/manifest.tmp" "$COLLISION/skill-topology.json"
jq '. += [{sourceId:"repo-claude",classification:"repo-owned",supportedDestinations:["claude","codex"],command:"adapters/repo-owned.sh"}]' \
  "$COLLISION/scripts/distribution-topology/registry.json" > "$COLLISION/registry.tmp"
mv "$COLLISION/registry.tmp" "$COLLISION/scripts/distribution-topology/registry.json"
: > "$COLLISION/npx.log"
set +e
run_topology "$COLLISION" "$COLLISION_UPSTREAM" "$COLLISION/result.json"
collision_exit=$?
set -e
test "$collision_exit" -eq 3
jq -e '.status == "decision-required" and (.decisions[] | .code == "surface-collision" and .skill == "alpha" and .destination == "claude")' \
  "$COLLISION/result.json" >/dev/null
test ! -s "$COLLISION/npx.log"

DIRECT_STAGE="$TMP_ROOT/direct-stage"
DIRECT_STAGE_UPSTREAM="$TMP_ROOT/direct-stage-upstream"
make_fixture "$DIRECT_STAGE" "$DIRECT_STAGE_UPSTREAM"
: > "$DIRECT_STAGE/npx.log"
run_topology "$DIRECT_STAGE" "$DIRECT_STAGE_UPSTREAM" "$DIRECT_STAGE/result.json" FAKE_NPX_PARTIAL=1
jq -e '.status == "reconciled" and .errors == []' "$DIRECT_STAGE/result.json" >/dev/null
test -f "$DIRECT_STAGE/other-skills/matt/new-skill/SKILL.md"
if grep -F 'add mattpocock/skills' "$DIRECT_STAGE/npx.log" >/dev/null; then exit 1; fi

echo "npx-distributed topology tests passed"
