#!/usr/bin/env bash

# Shared copy installers for update scripts.
# Skills from source-only clones are rsynced into a surface as COPIES — never
# symlinks. Copies landing in the repo's skills/ dir stay untracked via a
# marker-delimited .gitignore block regenerated on every run.
# Each copy carries a .agent-scripts-copy marker file so re-runs only ever
# overwrite directories this tooling created.

copy_warn() {
  printf '\033[0;31m!!!\033[0m %s\n' "$*" >&2
}

copy_info() {
  printf '\033[0;32m==>\033[0m %s\n' "$*"
}

install_skill_copy() { # source_dir dest_dir
  local src="$1"
  local dst="$2"
  local marker="${dst}/.agent-scripts-copy"

  if [ ! -d "$src" ]; then
    copy_warn "missing source: $src"
    return 1
  fi
  # Legacy state from the symlink era; replace with a real copy.
  if [ -L "$dst" ]; then
    unlink "$dst" || return 1
  elif [ -e "$dst" ] && [ ! -d "$dst" ]; then
    copy_warn "not a directory or symlink, refusing to replace: $dst"
    return 1
  elif [ -d "$dst" ] && [ ! -f "$marker" ]; then
    # Adopt copies older updaters generated: lib-links.sh fallback copies
    # carried .agent-scripts-copy-source; pre-marker rsync copies match their
    # upstream SKILL.md. Anything else non-empty is treated as user-owned.
    if [ -f "${dst}/.agent-scripts-copy-source" ]; then
      : # legacy fallback copy; the sync below replaces its marker with ours
    elif [ -f "${src}/SKILL.md" ] && [ -f "${dst}/SKILL.md" ] \
      && cmp -s "${src}/SKILL.md" "${dst}/SKILL.md"; then
      : # matches upstream; pre-marker generated copy
    elif [ -n "$(find "$dst" -mindepth 1 -maxdepth 1 2>/dev/null | head -1)" ]; then
      copy_warn "existing directory is not an agent-scripts copy, refusing to overwrite: $dst (delete it if an older updater generated it)"
      return 1
    fi
  fi
  mkdir -p "$dst" || return 1
  if [ "${AGENT_SCRIPTS_DISABLE_RSYNC:-0}" != "1" ] && command -v rsync >/dev/null 2>&1; then
    rsync -a --delete "${src}/" "${dst}/" || return 1
  else
    # Git Bash on Windows ships no rsync; emulate --delete with a fresh copy.
    rm -rf "$dst" || return 1
    mkdir -p "$dst" || return 1
    cp -R "${src}/." "${dst}/" || return 1
  fi
  printf '%s\n' "$src" > "$marker" || return 1
}

cleanup_marked_skill_copies() { # surface source_root keep_name...
  local surface="$1"
  local source_root="$2"
  shift 2
  local marker marker_source name keep keep_name failed=0

  if [ "$#" -eq 0 ]; then
    copy_warn "no current copy names for ${source_root}; refusing orphan cleanup under ${surface}"
    return 1
  fi

  [ -d "$surface" ] || return 0
  for marker in "$surface"/*/.agent-scripts-copy; do
    [ -f "$marker" ] || continue
    marker_source="$(sed -n '1p' "$marker")"
    case "$marker_source" in "${source_root}"/*) ;; *) continue ;; esac

    name="$(basename "$(dirname "$marker")")"
    keep=0
    for keep_name in "$@"; do
      if [ "$name" = "$keep_name" ]; then
        keep=1
        break
      fi
    done
    [ "$keep" -eq 0 ] || continue

    if rm -rf "${surface:?}/${name}"; then
      copy_info "removed orphaned copy: ${name}"
    else
      failed=1
    fi
  done
  return "$failed"
}

gitignore_block_skill_names() { # gitignore_path marker
  local gitignore="$1"
  local marker="$2"

  [ -f "$gitignore" ] || return 0
  awk -v start="# ${marker} start" -v end="# ${marker} end" '
    index($0, start) == 1 { in_block=1; next }
    $0 == end { in_block=0; next }
    in_block && $0 ~ /^skills\/[^/]+$/ {
      sub(/^skills\//, "")
      print
    }
  ' "$gitignore"
}

regen_gitignore_block() { # gitignore_path marker generator entry...
  local gitignore="$1"
  local marker="$2"
  local generator="$3"
  shift 3
  local block="# ${marker} start (generated by ${generator})"$'\n'
  local entry

  for entry in "$@"; do
    block="${block}${entry}"$'\n'
  done
  block="${block}# ${marker} end"

  touch "$gitignore"
  # An unterminated block would make the sed range below eat everything down
  # to EOF, including other blocks and hand-written rules.
  if grep -q "^# ${marker} start" "$gitignore" \
    && ! grep -q "^# ${marker} end$" "$gitignore"; then
    copy_warn "unterminated '# ${marker}' block in ${gitignore}; fix it by hand, not rewriting"
    return 1
  fi
  sed "/^# ${marker} start/,/^# ${marker} end$/d" "$gitignore" > "${gitignore}.tmp"
  printf '%s\n' "$block" >> "${gitignore}.tmp"
  mv "${gitignore}.tmp" "$gitignore"
}
