#!/usr/bin/env bash
set -euo pipefail

# Why Codex needs everything inlined, and why the result is tracked: README.md.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
AGENTS_MD="$REPO_ROOT/AGENTS.MD"
BUILT="$REPO_ROOT/AGENTS.codex.md"

if [ ! -f "$AGENTS_MD" ]; then
  printf 'error: shared instruction file missing: %s\n' "$AGENTS_MD" >&2
  exit 1
fi

build() {
  printf '<!-- Generated by agent-tooling/build-codex-instructions.sh. Edit AGENTS.MD or rules/, not this file. -->\n\n'
  cat "$AGENTS_MD" || return 1
  local rule
  for rule in "$REPO_ROOT"/rules/*.md; do
    [ -f "$rule" ] || continue
    printf '\n'
    cat "$rule" || return 1
  done
}

# Stage the build, then swap. Writing straight to $BUILT would truncate the
# tracked artifact on a partial build, and a later --check would compare that
# same partial output against itself and report up to date. Process
# substitution cannot carry the producer's exit status, so it cannot be used
# here either.
tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT
if ! build >"$tmp"; then
  printf 'error: build failed; %s left unchanged\n' "$BUILT" >&2
  exit 1
fi

if [ -f "$BUILT" ] && cmp -s "$tmp" "$BUILT"; then
  printf 'AGENTS.codex.md up to date\n'
  exit 0
fi

if [ "${1:-}" = "--check" ]; then
  printf 'error: AGENTS.codex.md is stale; run agent-tooling/build-codex-instructions.sh\n' >&2
  exit 1
fi

cp "$tmp" "$BUILT"
printf 'built %s\n' "$BUILT"
