#!/usr/bin/env bash
set -euo pipefail

# Why Codex needs everything inlined, and why the result is tracked: README.md.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
AGENTS_MD="$REPO_ROOT/AGENTS.MD"
BUILT="$REPO_ROOT/AGENTS.codex.md"

if [ ! -f "$AGENTS_MD" ]; then
  printf 'error: shared instruction file missing: %s\n' "$AGENTS_MD" >&2
  exit 1
fi

build() {
  printf '<!-- Generated by agent-tooling/build-codex-instructions.sh. Edit AGENTS.MD or rules/, not this file. -->\n\n'
  cat "$AGENTS_MD"
  local rule
  for rule in "$REPO_ROOT"/rules/*.md; do
    [ -f "$rule" ] || continue
    printf '\n'
    cat "$rule"
  done
}

if cmp -s <(build) "$BUILT" 2>/dev/null; then
  printf 'AGENTS.codex.md up to date\n'
  exit 0
fi

if [ "${1:-}" = "--check" ]; then
  printf 'error: AGENTS.codex.md is stale; run agent-tooling/build-codex-instructions.sh\n' >&2
  exit 1
fi

build > "$BUILT"
printf 'built %s\n' "$BUILT"
